services:
  mongo:
    image: mongo
    hostname: mongo_med_patente
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  web:
    build: 
      context: app
    container_name: med_patente
    environment:
        MONGO_INITDB_ROOT_USERNAME: example
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_HOST_NAME: mongo_med_patente
        SECRET_KEY_SESSION: b'8a665c57fc268229c8fa04aab499193063bd6b93eff981a361ad634e360ae755'
    stop_signal: SIGINT
    ports:
      - "5000:5000"